### ISSUE TITLE
Unable to log in with iPad Safari

### ISSUE THREAD

**Issue by hashrock** [odiak/draw#14]
- iPad OS 14.6, Safari
- Both Desktop Mode / Mobile Mode

After tapping "Sign in with Google", I get a "Failed to sign in" dialog.

**Comment by odiak** [comment]
Oh, I found this issue now. I'm sorry for late response.
I confirmed this on my iPad and I'll investigate it.

**Comment by odiak** [comment]
I found the cause of this issue.
The popup to sign in was blocked by Safari.

I fixed it to retry with redirection and deployed.
Thank you for reporting!
